//BASE PREFIX FOR BMSC PORTAL CARD LISTS
export const BMSC = "bmsc";

//BASE ACTIONS
export const UPDATE_STATE_ACTION = "UPDATE_STATE_ACTION";
export const UPDATE_STATE_ACTION_2 = "UPDATE_STATE_ACTION_2";
export const UPDATE_STATE_MUTATION = "UPDATE_STATE_MUTATION";
export const UPDATE_CARD_DATA_ACTION = "UPDATE_CARD_DATA_ACTION";
export const UPDATE_STATE_NEWS_ACTION = "UPDATE_STATE_NEWS_ACTION";
export const CONTACT_US_FORM_SEND = "CONTACT_US_FORM_SEND";
export const UPDATE_REAL_ESTATE_DATA = "UPDATE_REAL_ESTATE_DATA";
export const UPDATE_CAROUSEL_REAL_ESTATE_DATA = "UPDATE_CAROUSEL_REAL_ESTATE_DATA";
export const UPDATE_ESTATE_ITEM_DETAILS = "UPDATE_ESTATE_ITEM_DETAILS";
export const UPDATE_RELATED_ESTATE_ITEM_DETAILS = "UPDATE_RELATED_ESTATE_ITEM_DETAILS";
export const UPDATE_ITEM_DETAILS_CONTACT = "UPDATE_ITEM_DETAILS_CONTACT";

// NEWS actions
export const REQUEST_GET_NEWS = "REQUEST_GET_NEWS";
export const REQUEST_GET_NEWS_ENTRY = "REQUEST_GET_NEWS_ENTRY";
export const REQUEST_GET_FILTERED_NEWS = "REQUEST_GET_FILTERED_NEWS";
export const REQUEST_GET_NEWS_CATEGORIES = "REQUEST_GET_NEWS_CATEGORIES";
export const UPDATE_NEWS_LIST_CONTENT = "UPDATE_NEWS_LIST_CONTENT";
export const UPDATE_NEWS_CATEGORY_LIST_CONTENT =
  "UPDATE_NEWS_CATEGORY_LIST_CONTENT";

// FOOTER ACTIONS
export const UPDATE_TIPOTRE_ACTION = "UPDATE_TIPOTRE_ACTION";

// BENEFITS CLUB
export const REQUEST_GET_BENEFIT_CLUB_POINTS = "REQUEST_GET_BENEFIT_CLUB_POINTS";
export const REQUEST_GET_BENEFIT_CLUB_CITIES = "REQUEST_GET_BENEFIT_CLUB_CITIES";
export const REQUEST_GET_BENEFIT_CLUB_CATEGORIES = "REQUEST_GET_BENEFIT_CLUB_CATEGORIES";
export const REQUEST_GET_BENEFIT_CLUB_COMMERCES = "REQUEST_GET_BENEFIT_CLUB_COMMERCES";
export const UPDATE_BENEFIT_CLUB_POINTS_CONTENT = "UPDATE_BENEFIT_CLUB_POINTS_CONTENT";
export const UPDATE_BENEFIT_CLUB_CITIES_LIST = "UPDATE_BENEFIT_CLUB_CITIES_LIST";
export const UPDATE_BENEFIT_CLUB_CATEGORIES_LIST = "UPDATE_BENEFIT_CLUB_CATEGORIES_LIST";
export const UPDATE_BENEFIT_CLUB_COMMERCES_LIST = "REQUEST_GET_BENEFIT_CLUB_COMMERCES";
export const UPDATE_BENEFIT_CLUB_POINTS_ERROR = "UPDATE_BENEFIT_CLUB_POINTS_ERROR";

// BENEFITS DISCOUNT
export const REQUEST_GET_BENEFIT_DISCOUNT_CITIES = "REQUEST_GET_BENEFIT_DISCOUNT_CITIES";
export const REQUEST_GET_BENEFIT_DISCOUNT_CATEGORIES = "REQUEST_GET_BENEFIT_DISCOUNT_CATEGORIES";
export const REQUEST_GET_BENEFIT_DISCOUNT_COMMERCES = "REQUEST_GET_BENEFIT_DISCOUNT_COMMERCES";
export const UPDATE_BENEFIT_DISCOUNT_CITIES_LIST = "UPDATE_BENEFIT_DISCOUNT_CITIES_LIST";
export const UPDATE_BENEFIT_DISCOUNT_CATEGORIES_LIST = "UPDATE_BENEFIT_DISCOUNT_CATEGORIES_LIST";
export const UPDATE_BENEFIT_DISCOUNT_COMMERCES_LIST = "UPDATE_BENEFIT_DISCOUNT_COMMERCES_LIST";

// QUESTIONS actions
export const REQUEST_GET_CATEGORIES = "REQUEST_GET_CATEGORIES";
export const REQUEST_GET_QUESTIONS = "REQUEST_GET_QUESTIONS";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";

// PROMO BANX - PROMO RANKING
export const UPDATE_STATE_ACTION_RANKING_PROMO = "UPDATE_STATE_ACTION_RANKING_PROMO";

//ACCOUNT DETAILS
export const UPDATE_COUPONS_ERROR = "UPDATE_COUPONS_ERROR";

//simulate performance
 export const GET_SIMULATOR_INTEREST = 'GET_SIMULATOR_INTEREST'

//loan simulate
 export const GET_INFORMATION_INITIAL = 'GET_INFORMATION_INITIAL'
 export const GET_LOAN_SIMULATOR_CREDIT = 'GET_LOAN_SIMULATOR_CREDIT'
 export const GET_LOAN_SIMULATOR_CVS = 'GET_LOAN_SIMULATOR_CVS'
 export const GET_LOAN_SIMULATOR_DPF = 'GET_LOAN_SIMULATOR_DPF'
 export const GET_LOAN_SIMULATOR_DPF_INC = 'GET_LOAN_SIMULATOR_DPF_INC'
